version: '3.1'

services:

  mysql:
    image: mariadb
    volumes:
        - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: brainbow

  wordpress:
    image: wordpress
    volumes:
      - "./brainbow/:/var/www/html/wp-content/themes/brainbow/"
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: brainbow

  manifests:
    image: httpd
    volumes:
        - "./iiif/:/usr/local/apache2/htdocs/"
        - "./httpd.conf/:/usr/local/apache2/conf/httpd.conf"
    ports:
        - 8081:80
